# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
   vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  inputs:
    version: '1.13.5'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop

- script: |
    echo $PATH
    set
    sudo apt install wireless-tools wpasupplicant
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the Go workspace and packages'

- script: |
    echo $PATH
    set
    go version
    pwd
    sudo apt install wireless-tools wpasupplicant
    ls -l /sbin
    ls -l /usr/sbin
    echo HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
    echo $(build.repository.name)
    export GOPATH=$(pwd)/go
    export GO111MODULE=off
    echo $GOPATH
    echo $GO111MODULE
    echo $(pwd)
    echo azure can really make me mad
    ls -R
    PATH=$PATH:/usr/sbin:/sbin go get github.com/u-root/u-root
    ls -R
    PATH=$PATH:/usr/sbin:/sbin go get github.com/u-root/NiChrome/...
    ls -R
    PATH=$PATH:/usr/sbin:/sbin go get github.com/u-root/webboot
    ls -R
    cd go/src/github.com/u-root/webboot
    PATH=$PATH:/usr/sbin:/sbin go run github.com/u-root/webboot -c=all
    PATH=$PATH:/usr/sbin:/sbin go run github.com/u-root/webboot -u=-build=bb
    PATH=$PATH:/usr/sbin:/sbin go run github.com/u-root/webboot -c=all -u=-build=bb
  displayName: 'Get dependencies, then build'
