# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.12' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- script: |
    echo $PATH
    set
    sudo apt install wireless-tools wpasupplicant
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the Go workspace and packages'

- script: |
    echo $PATH
    set
    go version
    pwd
    sudo apt install wireless-tools wpasupplicant
    ls -l /sbin
    ls -l /usr/sbin
    echo $(build.repository.name)
    echo azure can really make me mad
    PATH=$PATH:/usr/sbin:/sbin go get github.com/u-root/u-root
    PATH=$PATH:/usr/sbin:/sbin go get github.com/u-root/NiChrome/...
    PATH=$PATH:/usr/sbin:/sbin go get github.com/u-root/webboot
    cd gopath/src/github.com/u-root/webboot
    PATH=$PATH:/usr/sbin:/sbin go run github.com/u-root/webboot -c=all
    PATH=$PATH:/usr/sbin:/sbin go run github.com/u-root/webboot -u=-build=bb
    PATH=$PATH:/usr/sbin:/sbin go run github.com/u-root/webboot -c=all -u=-build=bb
  displayName: 'Get dependencies, then build'
